/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdConfigInput {
  'placement' : AdPlacement,
  'name' : string,
  'targetUrl' : [] | [string],
  'isEnabled' : boolean,
  'imageUrl' : [] | [string],
  'adType' : AdType,
  'videoUrl' : [] | [string],
}
export interface AdConfigPublic {
  'id' : AdId,
  'placement' : AdPlacement,
  'name' : string,
  'targetUrl' : [] | [string],
  'isEnabled' : boolean,
  'imageUrl' : [] | [string],
  'adType' : AdType,
  'videoUrl' : [] | [string],
}
export type AdId = string;
export type AdPlacement = { 'postRoll' : null } |
  { 'preRoll' : null } |
  { 'homepage' : null } |
  { 'midRoll' : null };
export type AdType = { 'video' : null } |
  { 'banner' : null };
export type AnimeId = string;
export interface AnimeInput {
  'coverImageUrl' : string,
  'title' : string,
  'description' : string,
  'isFeatured' : boolean,
  'genres' : Array<string>,
  'rating' : number,
}
export interface AnimePublic {
  'id' : AnimeId,
  'coverImageUrl' : string,
  'title' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'viewCount' : bigint,
  'isFeatured' : boolean,
  'genres' : Array<string>,
  'rating' : number,
}
export interface AnimeRequest {
  'id' : string,
  'status' : string,
  'username' : string,
  'createdAt' : Timestamp,
  'requestText' : string,
}
export interface Comment {
  'id' : string,
  'authorUsername' : string,
  'isDeleted' : boolean,
  'authorId' : Principal,
  'createdAt' : Timestamp,
  'text' : string,
  'episodeId' : string,
  'updatedAt' : [] | [Timestamp],
  'parentId' : [] | [string],
}
export interface Episode {
  'id' : EpisodeId,
  'title' : string,
  'duration' : [] | [string],
  'thumbnailUrl' : [] | [string],
  'createdAt' : Timestamp,
  'description' : string,
  'seasonId' : [] | [SeasonId],
  'animeId' : AnimeId,
  'episodeNumber' : bigint,
  'videoUrl' : string,
}
export type EpisodeId = string;
export interface EpisodeInput {
  'title' : string,
  'duration' : [] | [string],
  'thumbnailUrl' : [] | [string],
  'description' : string,
  'seasonId' : [] | [SeasonId],
  'animeId' : AnimeId,
  'episodeNumber' : bigint,
  'videoUrl' : string,
}
export type SeasonId = string;
export interface SeasonInput {
  'name' : string,
  'animeId' : AnimeId,
  'seasonNumber' : bigint,
}
export interface SeasonPublic {
  'id' : SeasonId,
  'name' : string,
  'createdAt' : Timestamp,
  'animeId' : AnimeId,
  'seasonNumber' : bigint,
}
export type Timestamp = bigint;
export interface UserInput { 'username' : string, 'email' : [] | [string] }
export interface UserPublic {
  'id' : Principal,
  'username' : string,
  'createdAt' : Timestamp,
  'email' : [] | [string],
  'isAdmin' : boolean,
}
export interface WatchlistEntry {
  'userId' : Principal,
  'animeId' : AnimeId,
  'addedAt' : Timestamp,
}
export interface _SERVICE {
  'addComment' : ActorMethod<[string, string, [] | [string]], Comment>,
  'addRating' : ActorMethod<[string, bigint], [] | [string]>,
  'addToWatchlist' : ActorMethod<[string], undefined>,
  'addToWatchlistGuest' : ActorMethod<[string, string], undefined>,
  'aiChat' : ActorMethod<[string, string, string], string>,
  'createAdConfig' : ActorMethod<[AdConfigInput], AdConfigPublic>,
  'createAnime' : ActorMethod<[string, AnimeInput], AnimePublic>,
  'createEpisode' : ActorMethod<[string, EpisodeInput], Episode>,
  'createSeason' : ActorMethod<[string, SeasonInput], SeasonPublic>,
  'deleteAdConfig' : ActorMethod<[string], boolean>,
  'deleteAnime' : ActorMethod<[string, string], boolean>,
  'deleteAnimeRequest' : ActorMethod<[string, string], boolean>,
  'deleteComment' : ActorMethod<[string], boolean>,
  'deleteEpisode' : ActorMethod<[string, string], boolean>,
  'deleteSeason' : ActorMethod<[string, SeasonId], boolean>,
  'editComment' : ActorMethod<[string, string], [] | [Comment]>,
  'filterAnimeByGenre' : ActorMethod<[string], Array<AnimePublic>>,
  'getAdsByPlacement' : ActorMethod<[AdPlacement], Array<AdConfigPublic>>,
  'getAllAds' : ActorMethod<[], Array<AdConfigPublic>>,
  'getAllAnime' : ActorMethod<[], Array<AnimePublic>>,
  'getAllEpisodes' : ActorMethod<[], Array<Episode>>,
  'getAnime' : ActorMethod<[string], [] | [AnimePublic]>,
  'getAnimeRequests' : ActorMethod<[string], Array<AnimeRequest>>,
  'getCommentsByEpisode' : ActorMethod<[string], Array<Comment>>,
  'getEnabledAds' : ActorMethod<[], Array<AdConfigPublic>>,
  'getEpisode' : ActorMethod<[string], [] | [Episode]>,
  'getEpisodesByAnime' : ActorMethod<[string], Array<Episode>>,
  'getEpisodesBySeason' : ActorMethod<[SeasonId], Array<Episode>>,
  'getFeaturedAnime' : ActorMethod<[], Array<AnimePublic>>,
  'getGuestWatchlist' : ActorMethod<[string], Array<string>>,
  'getRatingsInfo' : ActorMethod<
    [string],
    { 'total' : bigint, 'average' : number, 'userRating' : [] | [bigint] }
  >,
  'getSeason' : ActorMethod<[SeasonId], [] | [SeasonPublic]>,
  'getSeasonsByAnime' : ActorMethod<[AnimeId], Array<SeasonPublic>>,
  'getUser' : ActorMethod<[], [] | [UserPublic]>,
  'getUserWatchlist' : ActorMethod<[], Array<WatchlistEntry>>,
  'incrementAnimeViewCount' : ActorMethod<[string], undefined>,
  'isAdminUser' : ActorMethod<[], boolean>,
  'isInWatchlist' : ActorMethod<[string], boolean>,
  'isInWatchlistGuest' : ActorMethod<[string, string], boolean>,
  'listAllUsers' : ActorMethod<[], Array<UserPublic>>,
  'markRequestComplete' : ActorMethod<[string, string], boolean>,
  'registerUser' : ActorMethod<[UserInput], UserPublic>,
  'removeFromWatchlist' : ActorMethod<[string], boolean>,
  'removeFromWatchlistGuest' : ActorMethod<[string, string], boolean>,
  'searchAnime' : ActorMethod<[string], Array<AnimePublic>>,
  'submitAnimeRequest' : ActorMethod<[string, string], string>,
  'updateAdConfig' : ActorMethod<
    [string, AdConfigInput],
    [] | [AdConfigPublic]
  >,
  'updateAnime' : ActorMethod<[string, string, AnimeInput], [] | [AnimePublic]>,
  'updateEpisode' : ActorMethod<[string, string, EpisodeInput], [] | [Episode]>,
  'updateSeason' : ActorMethod<
    [string, SeasonId, SeasonInput],
    [] | [SeasonPublic]
  >,
  'updateUser' : ActorMethod<[UserInput], [] | [UserPublic]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];