/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const Comment = IDL.Record({
  'id' : IDL.Text,
  'authorUsername' : IDL.Text,
  'isDeleted' : IDL.Bool,
  'authorId' : IDL.Principal,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'episodeId' : IDL.Text,
  'updatedAt' : IDL.Opt(Timestamp),
  'parentId' : IDL.Opt(IDL.Text),
});
export const AdPlacement = IDL.Variant({
  'postRoll' : IDL.Null,
  'preRoll' : IDL.Null,
  'homepage' : IDL.Null,
  'midRoll' : IDL.Null,
});
export const AdType = IDL.Variant({ 'video' : IDL.Null, 'banner' : IDL.Null });
export const AdConfigInput = IDL.Record({
  'placement' : AdPlacement,
  'name' : IDL.Text,
  'targetUrl' : IDL.Opt(IDL.Text),
  'isEnabled' : IDL.Bool,
  'imageUrl' : IDL.Opt(IDL.Text),
  'adType' : AdType,
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const AdId = IDL.Text;
export const AdConfigPublic = IDL.Record({
  'id' : AdId,
  'placement' : AdPlacement,
  'name' : IDL.Text,
  'targetUrl' : IDL.Opt(IDL.Text),
  'isEnabled' : IDL.Bool,
  'imageUrl' : IDL.Opt(IDL.Text),
  'adType' : AdType,
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const AnimeInput = IDL.Record({
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'genres' : IDL.Vec(IDL.Text),
  'rating' : IDL.Float64,
});
export const AnimeId = IDL.Text;
export const AnimePublic = IDL.Record({
  'id' : AnimeId,
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'viewCount' : IDL.Nat,
  'isFeatured' : IDL.Bool,
  'genres' : IDL.Vec(IDL.Text),
  'rating' : IDL.Float64,
});
export const SeasonId = IDL.Text;
export const EpisodeInput = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Opt(IDL.Text),
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'seasonId' : IDL.Opt(SeasonId),
  'animeId' : AnimeId,
  'episodeNumber' : IDL.Nat,
  'videoUrl' : IDL.Text,
});
export const EpisodeId = IDL.Text;
export const Episode = IDL.Record({
  'id' : EpisodeId,
  'title' : IDL.Text,
  'duration' : IDL.Opt(IDL.Text),
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'seasonId' : IDL.Opt(SeasonId),
  'animeId' : AnimeId,
  'episodeNumber' : IDL.Nat,
  'videoUrl' : IDL.Text,
});
export const SeasonInput = IDL.Record({
  'name' : IDL.Text,
  'animeId' : AnimeId,
  'seasonNumber' : IDL.Nat,
});
export const SeasonPublic = IDL.Record({
  'id' : SeasonId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'animeId' : AnimeId,
  'seasonNumber' : IDL.Nat,
});
export const AnimeRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'username' : IDL.Text,
  'createdAt' : Timestamp,
  'requestText' : IDL.Text,
});
export const UserPublic = IDL.Record({
  'id' : IDL.Principal,
  'username' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Opt(IDL.Text),
  'isAdmin' : IDL.Bool,
});
export const WatchlistEntry = IDL.Record({
  'userId' : IDL.Principal,
  'animeId' : AnimeId,
  'addedAt' : Timestamp,
});
export const UserInput = IDL.Record({
  'username' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addComment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Comment],
      [],
    ),
  'addRating' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Opt(IDL.Text)], []),
  'addToWatchlist' : IDL.Func([IDL.Text], [], []),
  'aiChat' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'createAdConfig' : IDL.Func([AdConfigInput], [AdConfigPublic], []),
  'createAnime' : IDL.Func([AnimeInput], [AnimePublic], []),
  'createEpisode' : IDL.Func([IDL.Text, EpisodeInput], [Episode], []),
  'createSeason' : IDL.Func([IDL.Text, SeasonInput], [SeasonPublic], []),
  'deleteAdConfig' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteAnime' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteAnimeRequest' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteComment' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteEpisode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteSeason' : IDL.Func([IDL.Text, SeasonId], [IDL.Bool], []),
  'editComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Comment)], []),
  'filterAnimeByGenre' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AnimePublic)],
      ['query'],
    ),
  'getAdsByPlacement' : IDL.Func(
      [AdPlacement],
      [IDL.Vec(AdConfigPublic)],
      ['query'],
    ),
  'getAllAds' : IDL.Func([], [IDL.Vec(AdConfigPublic)], ['query']),
  'getAllAnime' : IDL.Func([], [IDL.Vec(AnimePublic)], ['query']),
  'getAnime' : IDL.Func([IDL.Text], [IDL.Opt(AnimePublic)], ['query']),
  'getAnimeRequests' : IDL.Func([IDL.Text], [IDL.Vec(AnimeRequest)], ['query']),
  'getCommentsByEpisode' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getEnabledAds' : IDL.Func([], [IDL.Vec(AdConfigPublic)], ['query']),
  'getEpisode' : IDL.Func([IDL.Text], [IDL.Opt(Episode)], ['query']),
  'getEpisodesByAnime' : IDL.Func([IDL.Text], [IDL.Vec(Episode)], ['query']),
  'getEpisodesBySeason' : IDL.Func([SeasonId], [IDL.Vec(Episode)], ['query']),
  'getFeaturedAnime' : IDL.Func([], [IDL.Vec(AnimePublic)], ['query']),
  'getRatingsInfo' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'average' : IDL.Float64,
          'userRating' : IDL.Opt(IDL.Nat),
        }),
      ],
      ['query'],
    ),
  'getSeason' : IDL.Func([SeasonId], [IDL.Opt(SeasonPublic)], ['query']),
  'getSeasonsByAnime' : IDL.Func([AnimeId], [IDL.Vec(SeasonPublic)], ['query']),
  'getUser' : IDL.Func([], [IDL.Opt(UserPublic)], ['query']),
  'getUserWatchlist' : IDL.Func([], [IDL.Vec(WatchlistEntry)], ['query']),
  'incrementAnimeViewCount' : IDL.Func([IDL.Text], [], []),
  'isAdminUser' : IDL.Func([], [IDL.Bool], ['query']),
  'isInWatchlist' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserPublic)], ['query']),
  'markRequestComplete' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'registerUser' : IDL.Func([UserInput], [UserPublic], []),
  'removeFromWatchlist' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'searchAnime' : IDL.Func([IDL.Text], [IDL.Vec(AnimePublic)], ['query']),
  'submitAnimeRequest' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'updateAdConfig' : IDL.Func(
      [IDL.Text, AdConfigInput],
      [IDL.Opt(AdConfigPublic)],
      [],
    ),
  'updateAnime' : IDL.Func([IDL.Text, AnimeInput], [IDL.Opt(AnimePublic)], []),
  'updateEpisode' : IDL.Func(
      [IDL.Text, IDL.Text, EpisodeInput],
      [IDL.Opt(Episode)],
      [],
    ),
  'updateSeason' : IDL.Func(
      [IDL.Text, SeasonId, SeasonInput],
      [IDL.Opt(SeasonPublic)],
      [],
    ),
  'updateUser' : IDL.Func([UserInput], [IDL.Opt(UserPublic)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const Comment = IDL.Record({
    'id' : IDL.Text,
    'authorUsername' : IDL.Text,
    'isDeleted' : IDL.Bool,
    'authorId' : IDL.Principal,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'episodeId' : IDL.Text,
    'updatedAt' : IDL.Opt(Timestamp),
    'parentId' : IDL.Opt(IDL.Text),
  });
  const AdPlacement = IDL.Variant({
    'postRoll' : IDL.Null,
    'preRoll' : IDL.Null,
    'homepage' : IDL.Null,
    'midRoll' : IDL.Null,
  });
  const AdType = IDL.Variant({ 'video' : IDL.Null, 'banner' : IDL.Null });
  const AdConfigInput = IDL.Record({
    'placement' : AdPlacement,
    'name' : IDL.Text,
    'targetUrl' : IDL.Opt(IDL.Text),
    'isEnabled' : IDL.Bool,
    'imageUrl' : IDL.Opt(IDL.Text),
    'adType' : AdType,
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const AdId = IDL.Text;
  const AdConfigPublic = IDL.Record({
    'id' : AdId,
    'placement' : AdPlacement,
    'name' : IDL.Text,
    'targetUrl' : IDL.Opt(IDL.Text),
    'isEnabled' : IDL.Bool,
    'imageUrl' : IDL.Opt(IDL.Text),
    'adType' : AdType,
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const AnimeInput = IDL.Record({
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'genres' : IDL.Vec(IDL.Text),
    'rating' : IDL.Float64,
  });
  const AnimeId = IDL.Text;
  const AnimePublic = IDL.Record({
    'id' : AnimeId,
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'viewCount' : IDL.Nat,
    'isFeatured' : IDL.Bool,
    'genres' : IDL.Vec(IDL.Text),
    'rating' : IDL.Float64,
  });
  const SeasonId = IDL.Text;
  const EpisodeInput = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Opt(IDL.Text),
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'seasonId' : IDL.Opt(SeasonId),
    'animeId' : AnimeId,
    'episodeNumber' : IDL.Nat,
    'videoUrl' : IDL.Text,
  });
  const EpisodeId = IDL.Text;
  const Episode = IDL.Record({
    'id' : EpisodeId,
    'title' : IDL.Text,
    'duration' : IDL.Opt(IDL.Text),
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'seasonId' : IDL.Opt(SeasonId),
    'animeId' : AnimeId,
    'episodeNumber' : IDL.Nat,
    'videoUrl' : IDL.Text,
  });
  const SeasonInput = IDL.Record({
    'name' : IDL.Text,
    'animeId' : AnimeId,
    'seasonNumber' : IDL.Nat,
  });
  const SeasonPublic = IDL.Record({
    'id' : SeasonId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'animeId' : AnimeId,
    'seasonNumber' : IDL.Nat,
  });
  const AnimeRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'username' : IDL.Text,
    'createdAt' : Timestamp,
    'requestText' : IDL.Text,
  });
  const UserPublic = IDL.Record({
    'id' : IDL.Principal,
    'username' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Opt(IDL.Text),
    'isAdmin' : IDL.Bool,
  });
  const WatchlistEntry = IDL.Record({
    'userId' : IDL.Principal,
    'animeId' : AnimeId,
    'addedAt' : Timestamp,
  });
  const UserInput = IDL.Record({
    'username' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addComment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Comment],
        [],
      ),
    'addRating' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Opt(IDL.Text)], []),
    'addToWatchlist' : IDL.Func([IDL.Text], [], []),
    'aiChat' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'createAdConfig' : IDL.Func([AdConfigInput], [AdConfigPublic], []),
    'createAnime' : IDL.Func([AnimeInput], [AnimePublic], []),
    'createEpisode' : IDL.Func([IDL.Text, EpisodeInput], [Episode], []),
    'createSeason' : IDL.Func([IDL.Text, SeasonInput], [SeasonPublic], []),
    'deleteAdConfig' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteAnime' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteAnimeRequest' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteComment' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteEpisode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteSeason' : IDL.Func([IDL.Text, SeasonId], [IDL.Bool], []),
    'editComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Comment)], []),
    'filterAnimeByGenre' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AnimePublic)],
        ['query'],
      ),
    'getAdsByPlacement' : IDL.Func(
        [AdPlacement],
        [IDL.Vec(AdConfigPublic)],
        ['query'],
      ),
    'getAllAds' : IDL.Func([], [IDL.Vec(AdConfigPublic)], ['query']),
    'getAllAnime' : IDL.Func([], [IDL.Vec(AnimePublic)], ['query']),
    'getAnime' : IDL.Func([IDL.Text], [IDL.Opt(AnimePublic)], ['query']),
    'getAnimeRequests' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AnimeRequest)],
        ['query'],
      ),
    'getCommentsByEpisode' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Comment)],
        ['query'],
      ),
    'getEnabledAds' : IDL.Func([], [IDL.Vec(AdConfigPublic)], ['query']),
    'getEpisode' : IDL.Func([IDL.Text], [IDL.Opt(Episode)], ['query']),
    'getEpisodesByAnime' : IDL.Func([IDL.Text], [IDL.Vec(Episode)], ['query']),
    'getEpisodesBySeason' : IDL.Func([SeasonId], [IDL.Vec(Episode)], ['query']),
    'getFeaturedAnime' : IDL.Func([], [IDL.Vec(AnimePublic)], ['query']),
    'getRatingsInfo' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'average' : IDL.Float64,
            'userRating' : IDL.Opt(IDL.Nat),
          }),
        ],
        ['query'],
      ),
    'getSeason' : IDL.Func([SeasonId], [IDL.Opt(SeasonPublic)], ['query']),
    'getSeasonsByAnime' : IDL.Func(
        [AnimeId],
        [IDL.Vec(SeasonPublic)],
        ['query'],
      ),
    'getUser' : IDL.Func([], [IDL.Opt(UserPublic)], ['query']),
    'getUserWatchlist' : IDL.Func([], [IDL.Vec(WatchlistEntry)], ['query']),
    'incrementAnimeViewCount' : IDL.Func([IDL.Text], [], []),
    'isAdminUser' : IDL.Func([], [IDL.Bool], ['query']),
    'isInWatchlist' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserPublic)], ['query']),
    'markRequestComplete' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'registerUser' : IDL.Func([UserInput], [UserPublic], []),
    'removeFromWatchlist' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'searchAnime' : IDL.Func([IDL.Text], [IDL.Vec(AnimePublic)], ['query']),
    'submitAnimeRequest' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'updateAdConfig' : IDL.Func(
        [IDL.Text, AdConfigInput],
        [IDL.Opt(AdConfigPublic)],
        [],
      ),
    'updateAnime' : IDL.Func(
        [IDL.Text, AnimeInput],
        [IDL.Opt(AnimePublic)],
        [],
      ),
    'updateEpisode' : IDL.Func(
        [IDL.Text, IDL.Text, EpisodeInput],
        [IDL.Opt(Episode)],
        [],
      ),
    'updateSeason' : IDL.Func(
        [IDL.Text, SeasonId, SeasonInput],
        [IDL.Opt(SeasonPublic)],
        [],
      ),
    'updateUser' : IDL.Func([UserInput], [IDL.Opt(UserPublic)], []),
  });
};

export const init = ({ IDL }) => { return []; };