/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AdConfigPublic {
    id: AdId;
    placement: AdPlacement;
    name: string;
    targetUrl?: string;
    isEnabled: boolean;
    imageUrl?: string;
    adType: AdType;
    videoUrl?: string;
}
export type Timestamp = bigint;
export interface Comment {
    id: string;
    authorUsername: string;
    isDeleted: boolean;
    authorId: Principal;
    createdAt: Timestamp;
    text: string;
    episodeId: string;
    updatedAt?: Timestamp;
    parentId?: string;
}
export interface UserPublic {
    id: Principal;
    username: string;
    createdAt: Timestamp;
    email?: string;
    isAdmin: boolean;
}
export interface SeasonPublic {
    id: SeasonId;
    name: string;
    createdAt: Timestamp;
    animeId: AnimeId;
    seasonNumber: bigint;
}
export interface AnimePublic {
    id: AnimeId;
    coverImageUrl: string;
    title: string;
    createdAt: Timestamp;
    description: string;
    viewCount: bigint;
    isFeatured: boolean;
    genres: Array<string>;
    rating: number;
}
export interface AdConfigInput {
    placement: AdPlacement;
    name: string;
    targetUrl?: string;
    isEnabled: boolean;
    imageUrl?: string;
    adType: AdType;
    videoUrl?: string;
}
export interface Episode {
    id: EpisodeId;
    title: string;
    duration?: string;
    thumbnailUrl?: string;
    createdAt: Timestamp;
    description: string;
    seasonId?: SeasonId;
    animeId: AnimeId;
    episodeNumber: bigint;
    videoUrl: string;
}
export interface EpisodeInput {
    title: string;
    duration?: string;
    thumbnailUrl?: string;
    description: string;
    seasonId?: SeasonId;
    animeId: AnimeId;
    episodeNumber: bigint;
    videoUrl: string;
}
export interface AnimeRequest {
    id: string;
    status: string;
    username: string;
    createdAt: Timestamp;
    requestText: string;
}
export type SeasonId = string;
export interface AnimeInput {
    coverImageUrl: string;
    title: string;
    description: string;
    isFeatured: boolean;
    genres: Array<string>;
    rating: number;
}
export interface WatchlistEntry {
    userId: Principal;
    animeId: AnimeId;
    addedAt: Timestamp;
}
export type AnimeId = string;
export interface UserInput {
    username: string;
    email?: string;
}
export interface SeasonInput {
    name: string;
    animeId: AnimeId;
    seasonNumber: bigint;
}
export type EpisodeId = string;
export type AdId = string;
export enum AdPlacement {
    postRoll = "postRoll",
    preRoll = "preRoll",
    homepage = "homepage",
    midRoll = "midRoll"
}
export enum AdType {
    video = "video",
    banner = "banner"
}
export interface backendInterface {
    addComment(episodeId: string, text: string, parentId: string | null): Promise<Comment>;
    addRating(episodeId: string, stars: bigint): Promise<string | null>;
    addToWatchlist(animeId: string): Promise<void>;
    aiChat(userMessage: string, pageContext: string, errorContext: string): Promise<string>;
    createAdConfig(input: AdConfigInput): Promise<AdConfigPublic>;
    createAnime(input: AnimeInput): Promise<AnimePublic>;
    createEpisode(adminToken: string, input: EpisodeInput): Promise<Episode>;
    createSeason(adminToken: string, input: SeasonInput): Promise<SeasonPublic>;
    deleteAdConfig(id: string): Promise<boolean>;
    deleteAnime(id: string): Promise<boolean>;
    deleteAnimeRequest(id: string, adminToken: string): Promise<boolean>;
    deleteComment(commentId: string): Promise<boolean>;
    deleteEpisode(adminToken: string, id: string): Promise<boolean>;
    deleteSeason(adminToken: string, id: SeasonId): Promise<boolean>;
    editComment(commentId: string, newText: string): Promise<Comment | null>;
    filterAnimeByGenre(genre: string): Promise<Array<AnimePublic>>;
    getAdsByPlacement(placement: AdPlacement): Promise<Array<AdConfigPublic>>;
    getAllAds(): Promise<Array<AdConfigPublic>>;
    getAllAnime(): Promise<Array<AnimePublic>>;
    getAnime(id: string): Promise<AnimePublic | null>;
    getAnimeRequests(adminToken: string): Promise<Array<AnimeRequest>>;
    getCommentsByEpisode(episodeId: string): Promise<Array<Comment>>;
    getEnabledAds(): Promise<Array<AdConfigPublic>>;
    getEpisode(id: string): Promise<Episode | null>;
    getEpisodesByAnime(animeId: string): Promise<Array<Episode>>;
    getEpisodesBySeason(seasonId: SeasonId): Promise<Array<Episode>>;
    getFeaturedAnime(): Promise<Array<AnimePublic>>;
    getRatingsInfo(episodeId: string): Promise<{
        total: bigint;
        average: number;
        userRating?: bigint;
    }>;
    getSeason(id: SeasonId): Promise<SeasonPublic | null>;
    getSeasonsByAnime(animeId: AnimeId): Promise<Array<SeasonPublic>>;
    getUser(): Promise<UserPublic | null>;
    getUserWatchlist(): Promise<Array<WatchlistEntry>>;
    incrementAnimeViewCount(id: string): Promise<void>;
    isAdminUser(): Promise<boolean>;
    isInWatchlist(animeId: string): Promise<boolean>;
    listAllUsers(): Promise<Array<UserPublic>>;
    markRequestComplete(id: string, adminToken: string): Promise<boolean>;
    registerUser(input: UserInput): Promise<UserPublic>;
    removeFromWatchlist(animeId: string): Promise<boolean>;
    searchAnime(term: string): Promise<Array<AnimePublic>>;
    submitAnimeRequest(requestText: string, username: string): Promise<string>;
    updateAdConfig(id: string, input: AdConfigInput): Promise<AdConfigPublic | null>;
    updateAnime(id: string, input: AnimeInput): Promise<AnimePublic | null>;
    updateEpisode(adminToken: string, id: string, input: EpisodeInput): Promise<Episode | null>;
    updateSeason(adminToken: string, id: SeasonId, input: SeasonInput): Promise<SeasonPublic | null>;
    updateUser(input: UserInput): Promise<UserPublic | null>;
}
import type { AdConfigInput as _AdConfigInput, AdConfigPublic as _AdConfigPublic, AdId as _AdId, AdPlacement as _AdPlacement, AdType as _AdType, AnimeId as _AnimeId, AnimePublic as _AnimePublic, Comment as _Comment, Episode as _Episode, EpisodeId as _EpisodeId, EpisodeInput as _EpisodeInput, SeasonId as _SeasonId, SeasonPublic as _SeasonPublic, Timestamp as _Timestamp, UserInput as _UserInput, UserPublic as _UserPublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addComment(arg0: string, arg1: string, arg2: string | null): Promise<Comment> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Comment_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Comment_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async addRating(arg0: string, arg1: bigint): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addRating(arg0, arg1);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRating(arg0, arg1);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addToWatchlist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWatchlist(arg0);
            return result;
        }
    }
    async aiChat(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.aiChat(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.aiChat(arg0, arg1, arg2);
            return result;
        }
    }
    async createAdConfig(arg0: AdConfigInput): Promise<AdConfigPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createAdConfig(to_candid_AdConfigInput_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AdConfigPublic_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAdConfig(to_candid_AdConfigInput_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AdConfigPublic_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createAnime(arg0: AnimeInput): Promise<AnimePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnime(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnime(arg0);
            return result;
        }
    }
    async createEpisode(arg0: string, arg1: EpisodeInput): Promise<Episode> {
        if (this.processError) {
            try {
                const result = await this.actor.createEpisode(arg0, to_candid_EpisodeInput_n18(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Episode_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEpisode(arg0, to_candid_EpisodeInput_n18(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Episode_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSeason(arg0: string, arg1: SeasonInput): Promise<SeasonPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createSeason(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSeason(arg0, arg1);
            return result;
        }
    }
    async deleteAdConfig(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAdConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAdConfig(arg0);
            return result;
        }
    }
    async deleteAnime(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnime(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnime(arg0);
            return result;
        }
    }
    async deleteAnimeRequest(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnimeRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnimeRequest(arg0, arg1);
            return result;
        }
    }
    async deleteComment(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async deleteEpisode(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEpisode(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEpisode(arg0, arg1);
            return result;
        }
    }
    async deleteSeason(arg0: string, arg1: SeasonId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSeason(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSeason(arg0, arg1);
            return result;
        }
    }
    async editComment(arg0: string, arg1: string): Promise<Comment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.editComment(arg0, arg1);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editComment(arg0, arg1);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterAnimeByGenre(arg0: string): Promise<Array<AnimePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterAnimeByGenre(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterAnimeByGenre(arg0);
            return result;
        }
    }
    async getAdsByPlacement(arg0: AdPlacement): Promise<Array<AdConfigPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdsByPlacement(to_candid_AdPlacement_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdsByPlacement(to_candid_AdPlacement_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAds(): Promise<Array<AdConfigPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAds();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAds();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAnime(): Promise<Array<AnimePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnime();
            return result;
        }
    }
    async getAnime(arg0: string): Promise<AnimePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnime(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnime(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnimeRequests(arg0: string): Promise<Array<AnimeRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnimeRequests(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnimeRequests(arg0);
            return result;
        }
    }
    async getCommentsByEpisode(arg0: string): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommentsByEpisode(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommentsByEpisode(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEnabledAds(): Promise<Array<AdConfigPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnabledAds();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnabledAds();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEpisode(arg0: string): Promise<Episode | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEpisode(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEpisode(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEpisodesByAnime(arg0: string): Promise<Array<Episode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEpisodesByAnime(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEpisodesByAnime(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEpisodesBySeason(arg0: SeasonId): Promise<Array<Episode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEpisodesBySeason(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEpisodesBySeason(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedAnime(): Promise<Array<AnimePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedAnime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedAnime();
            return result;
        }
    }
    async getRatingsInfo(arg0: string): Promise<{
        total: bigint;
        average: number;
        userRating?: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getRatingsInfo(arg0);
                return from_candid_record_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRatingsInfo(arg0);
            return from_candid_record_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSeason(arg0: SeasonId): Promise<SeasonPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSeason(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSeason(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSeasonsByAnime(arg0: AnimeId): Promise<Array<SeasonPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSeasonsByAnime(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSeasonsByAnime(arg0);
            return result;
        }
    }
    async getUser(): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserWatchlist(): Promise<Array<WatchlistEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserWatchlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserWatchlist();
            return result;
        }
    }
    async incrementAnimeViewCount(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementAnimeViewCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementAnimeViewCount(arg0);
            return result;
        }
    }
    async isAdminUser(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminUser();
            return result;
        }
    }
    async isInWatchlist(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isInWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isInWatchlist(arg0);
            return result;
        }
    }
    async listAllUsers(): Promise<Array<UserPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async markRequestComplete(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markRequestComplete(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markRequestComplete(arg0, arg1);
            return result;
        }
    }
    async registerUser(arg0: UserInput): Promise<UserPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(to_candid_UserInput_n36(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserPublic_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(to_candid_UserInput_n36(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserPublic_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromWatchlist(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWatchlist(arg0);
            return result;
        }
    }
    async searchAnime(arg0: string): Promise<Array<AnimePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchAnime(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchAnime(arg0);
            return result;
        }
    }
    async submitAnimeRequest(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAnimeRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAnimeRequest(arg0, arg1);
            return result;
        }
    }
    async updateAdConfig(arg0: string, arg1: AdConfigInput): Promise<AdConfigPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdConfig(arg0, to_candid_AdConfigInput_n6(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdConfig(arg0, to_candid_AdConfigInput_n6(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAnime(arg0: string, arg1: AnimeInput): Promise<AnimePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnime(arg0, arg1);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnime(arg0, arg1);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateEpisode(arg0: string, arg1: string, arg2: EpisodeInput): Promise<Episode | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEpisode(arg0, arg1, to_candid_EpisodeInput_n18(this._uploadFile, this._downloadFile, arg2));
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEpisode(arg0, arg1, to_candid_EpisodeInput_n18(this._uploadFile, this._downloadFile, arg2));
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSeason(arg0: string, arg1: SeasonId, arg2: SeasonInput): Promise<SeasonPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSeason(arg0, arg1, arg2);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSeason(arg0, arg1, arg2);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUser(arg0: UserInput): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(to_candid_UserInput_n36(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(to_candid_UserInput_n36(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AdConfigPublic_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdConfigPublic): AdConfigPublic {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_AdPlacement_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdPlacement): AdPlacement {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_AdType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdType): AdType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Comment_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Comment): Comment {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Episode_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Episode): Episode {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserPublic_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPublic): UserPublic {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SeasonId]): SeasonId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Comment]): Comment | null {
    return value.length === 0 ? null : from_candid_Comment_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AnimePublic]): AnimePublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Episode]): Episode | null {
    return value.length === 0 ? null : from_candid_Episode_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SeasonPublic]): SeasonPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPublic]): UserPublic | null {
    return value.length === 0 ? null : from_candid_UserPublic_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdConfigPublic]): AdConfigPublic | null {
    return value.length === 0 ? null : from_candid_AdConfigPublic_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AdId;
    placement: _AdPlacement;
    name: string;
    targetUrl: [] | [string];
    isEnabled: boolean;
    imageUrl: [] | [string];
    adType: _AdType;
    videoUrl: [] | [string];
}): {
    id: AdId;
    placement: AdPlacement;
    name: string;
    targetUrl?: string;
    isEnabled: boolean;
    imageUrl?: string;
    adType: AdType;
    videoUrl?: string;
} {
    return {
        id: value.id,
        placement: from_candid_AdPlacement_n14(_uploadFile, _downloadFile, value.placement),
        name: value.name,
        targetUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.targetUrl)),
        isEnabled: value.isEnabled,
        imageUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.imageUrl)),
        adType: from_candid_AdType_n16(_uploadFile, _downloadFile, value.adType),
        videoUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.videoUrl))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EpisodeId;
    title: string;
    duration: [] | [string];
    thumbnailUrl: [] | [string];
    createdAt: _Timestamp;
    description: string;
    seasonId: [] | [_SeasonId];
    animeId: _AnimeId;
    episodeNumber: bigint;
    videoUrl: string;
}): {
    id: EpisodeId;
    title: string;
    duration?: string;
    thumbnailUrl?: string;
    createdAt: Timestamp;
    description: string;
    seasonId?: SeasonId;
    animeId: AnimeId;
    episodeNumber: bigint;
    videoUrl: string;
} {
    return {
        id: value.id,
        title: value.title,
        duration: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.duration)),
        thumbnailUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.thumbnailUrl)),
        createdAt: value.createdAt,
        description: value.description,
        seasonId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.seasonId)),
        animeId: value.animeId,
        episodeNumber: value.episodeNumber,
        videoUrl: value.videoUrl
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    average: number;
    userRating: [] | [bigint];
}): {
    total: bigint;
    average: number;
    userRating?: bigint;
} {
    return {
        total: value.total,
        average: value.average,
        userRating: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.userRating))
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    authorUsername: string;
    isDeleted: boolean;
    authorId: Principal;
    createdAt: _Timestamp;
    text: string;
    episodeId: string;
    updatedAt: [] | [_Timestamp];
    parentId: [] | [string];
}): {
    id: string;
    authorUsername: string;
    isDeleted: boolean;
    authorId: Principal;
    createdAt: Timestamp;
    text: string;
    episodeId: string;
    updatedAt?: Timestamp;
    parentId?: string;
} {
    return {
        id: value.id,
        authorUsername: value.authorUsername,
        isDeleted: value.isDeleted,
        authorId: value.authorId,
        createdAt: value.createdAt,
        text: value.text,
        episodeId: value.episodeId,
        updatedAt: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.updatedAt)),
        parentId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.parentId))
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    username: string;
    createdAt: _Timestamp;
    email: [] | [string];
    isAdmin: boolean;
}): {
    id: Principal;
    username: string;
    createdAt: Timestamp;
    email?: string;
    isAdmin: boolean;
} {
    return {
        id: value.id,
        username: value.username,
        createdAt: value.createdAt,
        email: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.email)),
        isAdmin: value.isAdmin
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    postRoll: null;
} | {
    preRoll: null;
} | {
    homepage: null;
} | {
    midRoll: null;
}): AdPlacement {
    return "postRoll" in value ? AdPlacement.postRoll : "preRoll" in value ? AdPlacement.preRoll : "homepage" in value ? AdPlacement.homepage : "midRoll" in value ? AdPlacement.midRoll : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    banner: null;
}): AdType {
    return "video" in value ? AdType.video : "banner" in value ? AdType.banner : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdConfigPublic>): Array<AdConfigPublic> {
    return value.map((x)=>from_candid_AdConfigPublic_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Comment>): Array<Comment> {
    return value.map((x)=>from_candid_Comment_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Episode>): Array<Episode> {
    return value.map((x)=>from_candid_Episode_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserPublic>): Array<UserPublic> {
    return value.map((x)=>from_candid_UserPublic_n33(_uploadFile, _downloadFile, x));
}
function to_candid_AdConfigInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdConfigInput): _AdConfigInput {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_AdPlacement_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdPlacement): _AdPlacement {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_AdType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdType): _AdType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_EpisodeInput_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EpisodeInput): _EpisodeInput {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserInput_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserInput): _UserInput {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    duration?: string;
    thumbnailUrl?: string;
    description: string;
    seasonId?: SeasonId;
    animeId: AnimeId;
    episodeNumber: bigint;
    videoUrl: string;
}): {
    title: string;
    duration: [] | [string];
    thumbnailUrl: [] | [string];
    description: string;
    seasonId: [] | [_SeasonId];
    animeId: _AnimeId;
    episodeNumber: bigint;
    videoUrl: string;
} {
    return {
        title: value.title,
        duration: value.duration ? candid_some(value.duration) : candid_none(),
        thumbnailUrl: value.thumbnailUrl ? candid_some(value.thumbnailUrl) : candid_none(),
        description: value.description,
        seasonId: value.seasonId ? candid_some(value.seasonId) : candid_none(),
        animeId: value.animeId,
        episodeNumber: value.episodeNumber,
        videoUrl: value.videoUrl
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    email?: string;
}): {
    username: string;
    email: [] | [string];
} {
    return {
        username: value.username,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    placement: AdPlacement;
    name: string;
    targetUrl?: string;
    isEnabled: boolean;
    imageUrl?: string;
    adType: AdType;
    videoUrl?: string;
}): {
    placement: _AdPlacement;
    name: string;
    targetUrl: [] | [string];
    isEnabled: boolean;
    imageUrl: [] | [string];
    adType: _AdType;
    videoUrl: [] | [string];
} {
    return {
        placement: to_candid_AdPlacement_n8(_uploadFile, _downloadFile, value.placement),
        name: value.name,
        targetUrl: value.targetUrl ? candid_some(value.targetUrl) : candid_none(),
        isEnabled: value.isEnabled,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        adType: to_candid_AdType_n10(_uploadFile, _downloadFile, value.adType),
        videoUrl: value.videoUrl ? candid_some(value.videoUrl) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdType): {
    video: null;
} | {
    banner: null;
} {
    return value == AdType.video ? {
        video: null
    } : value == AdType.banner ? {
        banner: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdPlacement): {
    postRoll: null;
} | {
    preRoll: null;
} | {
    homepage: null;
} | {
    midRoll: null;
} {
    return value == AdPlacement.postRoll ? {
        postRoll: null
    } : value == AdPlacement.preRoll ? {
        preRoll: null
    } : value == AdPlacement.homepage ? {
        homepage: null
    } : value == AdPlacement.midRoll ? {
        midRoll: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
